Add postinst for migrating boot configuration
Detect the old (single file) boot configuration and, if required,
migrate to the new (multi-file, selective) boot config.

diff --git a/debian/u-boot-rpi.postinst b/debian/u-boot-rpi.postinst
--- a/debian/u-boot-rpi.postinst
+++ b/debian/u-boot-rpi.postinst
@@ -2,37 +2,36 @@
 
 set -e
 
+BOOT="/boot/firmware"
+
+. /usr/share/u-boot/rpi-config-migration
+
 case "$1" in
   configure)
     if ! ischroot; then
-      if ! mountpoint -q /boot/firmware; then
-        echo "Error: missing /boot/firmware, did you forget to mount it?" >&2
+      if ! mountpoint -q "$BOOT"; then
+        echo "Error: missing $BOOT, did you forget to mount it?" >&2
         exit 1
       fi
     fi
 
-    # The u-boot-rpi package now ships more than just one u-boot binary.
-    # We need to determine which supported Pi platform we're running on and
-    # use the right uboot binary for the upgrade, defaulting to Pi 2 (as we
-    # did previously).
-    DEVICES="rpi_2"
-    if [ -e /proc/device-tree/model ] && grep -q "Pi 3" /proc/device-tree/model; then
-      DEVICES="rpi_3 rpi_3_32b"
-    fi
-    for device in $DEVICES; do
-      BIN_PATH=/usr/lib/u-boot/$device/u-boot.bin
-      if [ -f $BIN_PATH ]; then
-        # In case of Pi3 on arm64, the uboot binary needs to be named
-        # kernel8.img.
-        if [ "$device" = "rpi_3" ]; then
-          TARGET_BINARY="kernel8.img"
-        else
-          TARGET_BINARY="uboot.bin"
-        fi
-        cp $BIN_PATH /boot/firmware/$TARGET_BINARY
-        break
-      fi
+    # The u-boot-rpi package now ships more than just one u-boot binary. Copy
+    # all supported u-boot binaries to the boot partition to support the
+    # case of switching the SD card between Pis
+    for uboot_binary in /usr/lib/u-boot/*/u-boot.bin; do
+        dest_binary=uboot_$(basename $(dirname "$uboot_binary")).bin
+        cp "$uboot_binary" "$BOOT/$dest_binary"
     done
+
+    # If necessary, migrate boot configuration from the pre-eoan default
+    # configuration (monolithic config.txt, single u-boot binary) to the new
+    # style (modular selective config.txt, multiple u-boot binaries)
+    if dpkg --compare-versions "$2" lt "2019.07+dfsg-1ubuntu1~" && is_old_config; then
+        echo -n "Migrating boot configuration..."
+        migrate_config
+        echo "done"
+        echo "Old configuration has been preserved in $BOOT/config.bak"
+    fi
     ;;
 esac
 
